## Dracula theme
idle_bg = "#282936"
idle_fg = "#e9e9f4"
info_bg = "#e9e9f4"
info_fg = "#626483"
# good_bg = "#ebff87"
# good_fg = "#282936"
good_bg = "#6272a4"
good_fg = "#f8f8f2"
critical_bg = "#ea51b2"
warning_bg = "#b45bcf"
warning_fg = "#002b36"
critical_fg = "#002b36"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
alternating_tint_bg = "#000000"
alternating_tint_fg = "#000000"
