## Nord theme
idle_bg = "#2e3440"
idle_fg = "#e5e9f0"
info_bg = "#8fbcbb"
info_fg = "#3b4252"
good_bg = "#8fbcbb"
good_fg = "#2e3440"
critical_bg = "#bf616a"
warning_bg = "#b48ead"
warning_fg = "#002b36"
critical_fg = "#002b36"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
alternating_tint_bg = "#000000"
alternating_tint_fg = "#000000"
