image: archlinux
packages:
  - emacs-nox
oauth: pages.sr.ht/PAGES:RW
sources:
  - https://git.sr.ht/~daviwil/dotfiles
  - https://git.sr.ht/~daviwil/daviwil.com
environment:
  site: config.daviwil.com
secrets:
  - 5269a80d-deda-4fc5-bcfb-d05b10b3cef0
tasks:
  - mirror: |
      cd dotfiles
      git remote add github git@github.com:daviwil/dotfiles
      ssh-keyscan github.com >> ~/.ssh/known_hosts
      git push -f github master
  - build: |
      cd dotfiles/.site
      cp -R ../../daviwil.com/public .
      emacs --batch -l ./publish.el --funcall dw/publish
      cd public
      tar -cvz . > ../../../site.tar.gz
  - upload: |
      acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz
