- name: update
  sudo: yes
  apt: 
    update_cache: yes 
    cache_valid_time: 3600

- name: install dialog
  apt:
      name: "dialog"
      state: present

- name: install wget
  apt:
      name: "wget"
      state: present

- name: install curl
  apt:
      name: "curl"
      state: present

- name: install git
  apt:
      name: "git"
      state: present

- name: install tmux
  apt:
      name: "tmux"
      state: present
      