version: 4

services:
    trojan:
      image: gists/trojan-go
      container_name: trojan-go
      links:
        - nginx
      ports:
        - "443:443"
      volumes:
        - ./config.json:/etc/trojan-go/config.json
        - ./fullchain.cer:/fullchain.cer
        - ./private.key:/private.key
      restart: always   
    nginx:
      image: nginx
      container_name: nginx
      ports:
        - "80:80"
      volumes:
        - ./nginx.json:/etc/nginx.json
      restart: always
