#!/bin/sh
case $(hostname) in

    vagrant)
	xrandr --output eDP-1 --primary --mode 1366x768 --pos 0x0 --rotate normal --output HDMI-1 --mode 1920x1080 --pos 1366x0 --rotate normal --output DP-1 --off
        ;;
    debian)
	xrandr --output eDP-1 --primary --mode 1366x768 --pos 0x0 --rotate normal --output HDMI-1 --mode 1920x1080 --pos 1366x0 --rotate normal --output DP-1 --off
        ;;

esac
