Vagrant.configure("2") do |config|
  config.vm.box = "alpine/alpine64"
  config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 22, host: 8022
end